server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: User
          uri: http://localhost:8081
          predicates:
            - Path=/user/** 
        - id: Dashboard
          uri: http://localhost:8082
          predicates:
            - Path= /dashboard/**
        - id: Reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservation/** 
        - id: Hospital
          uri: http://localhost:8084
          predicates:
            - Path=/hospital/** 
        - id: VaccineStock
          uri: http://localhost:8085
          predicates:
            - Path=/stock/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: User
          uri: http://User:8080
          predicates:
            - Path=/user/** 
        - id: Dashboard
          uri: http://Dashboard:8080
          predicates:
            - Path= /dashboard/**
        - id: Reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/reservation/** 
        - id: Hospital
          uri: http://Hospital:8080
          predicates:
            - Path=/hospital/** 
        - id: VaccineStock
          uri: http://VaccineStock:8080
          predicates:
            - Path=/stock/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080