server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: User
          uri: http://localhost:8081
          predicates:
            - Path=/users/** 
        - id: Dashboard
          uri: http://localhost:8082
          predicates:
            - Path= /dashboards/**
        - id: Reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/** 
        - id: Hospital
          uri: http://localhost:8084
          predicates:
            - Path=/reservations/** 
        - id: VaccineStock
          uri: http://localhost:8085
          predicates:
            - Path=/stocks/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: User
          uri: http://User:8080
          predicates:
            - Path=/users/** 
        - id: Dashboard
          uri: http://Dashboard:8080
          predicates:
            - Path= /dashboards/**
        - id: Reservation
          uri: http://Reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: Hospital
          uri: http://Hospital:8080
          predicates:
            - Path=/reservations/** 
        - id: VaccineStock
          uri: http://VaccineStock:8080
          predicates:
            - Path=/stocks/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080