apiVersion: apps/v1
kind: Deployment
metadata:
  name: VaccineStock
  labels:
    app: VaccineStock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VaccineStock
  template:
    metadata:
      labels:
        app: VaccineStock
    spec:
      containers:
        - name: VaccineStock
          image: username/VaccineStock:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5